# Generated by Django 5.1.6 on 2025-02-11 07:52

import datetime
import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Полное наименование')),
                ('slug', models.SlugField(max_length=25, unique=True, verbose_name='Slug')),
                ('is_enabled', models.BooleanField(default=False, verbose_name='Включен')),
                ('description', models.CharField(blank=True, max_length=100, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Сенсор',
                'verbose_name_plural': 'Сенсоры',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SensorStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('value_from', models.FloatField(verbose_name='Значение с')),
                ('value_to', models.FloatField(verbose_name='Значение до')),
                ('duration_from', models.DurationField(default=datetime.timedelta(0), verbose_name='Длительность с')),
                ('duration_to', models.DurationField(blank=True, null=True, verbose_name='Длительность до')),
                ('need_comment', models.BooleanField(verbose_name='Необходим комментарий')),
                ('color', models.CharField(help_text='html цвет, например #4285f4', max_length=7, verbose_name='Цвет')),
                ('status_type', models.CharField(choices=[('WORK', 'Работа'), ('PAUSE', 'Тех. пауза'), ('STOP', 'Остановка'), ('OFFLINE', 'Отключен')], max_length=15, verbose_name='Тип статуса')),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='sensors.sensor', verbose_name='Сенсор')),
            ],
            options={
                'verbose_name': 'Состояние сенсора',
                'verbose_name_plural': 'Состояния сенсоров',
                'ordering': ['name'],
            },
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='StatusReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=100, verbose_name='Причина состояния')),
                ('group', models.CharField(blank=True, max_length=50, verbose_name='Группа')),
                ('priority', models.PositiveSmallIntegerField(default=32767, verbose_name='Приоритет')),
                ('sensor_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reasons', to='sensors.sensorstatus', verbose_name='Состояние сенсора')),
            ],
            options={
                'verbose_name': 'Причина состояния',
                'verbose_name_plural': 'Причины состояний',
                'ordering': ['group', 'priority', 'reason'],
            },
        ),
        migrations.CreateModel(
            name='WorkCenterType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('description', models.CharField()),
                ('default_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='sensors.sensorstatus', verbose_name='Статус по умолчанию')),
            ],
        ),
        migrations.CreateModel(
            name='WorkingInterval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(verbose_name='С')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='До')),
                ('last_reading_value', models.FloatField(verbose_name='Крайнее измеренное значение')),
                ('last_reading_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата крайнего измеренного значения')),
                ('comment', models.CharField(blank=True, max_length=200, verbose_name='Комментарий')),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='working_intervals', to='sensors.sensor', verbose_name='Сенсор')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sensors.sensorstatus', verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Рабочий интервал',
                'verbose_name_plural': 'Рабочие интервалы',
                'ordering': ['started_at'],
            },
        ),
        migrations.CreateModel(
            name='SensorReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(verbose_name='Значение')),
                ('measured_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата и время измерения')),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='sensors.sensor', verbose_name='Сенсор')),
                ('working_interval', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='sensors.workinginterval', verbose_name='Измерения')),
            ],
            options={
                'verbose_name': 'Измерение',
                'verbose_name_plural': 'Измерения',
                'ordering': ['measured_at'],
            },
        ),
    ]
