# Generated by Django 5.1.6 on 2025-02-13 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='SensorStatus',
            name='status_type',
            field=models.CharField(choices=[('WORK', 'Работа'), ('PAUSE', 'Тех. пауза'), ('STOP', 'Остановка'), ('OFFLINE', 'Отключен'), ('UNKNOWN', 'Неизвестный')], max_length=15, verbose_name='Тип статуса'),
        ),
    ]
