# Generated by Django 4.2.4 on 2025-01-27 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0006_alter_sensorstatus_managers_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sensorstatus',
            options={'ordering': ['name'], 'verbose_name': 'Состояние сенсора', 'verbose_name_plural': 'Состояния сенсоров'},
        ),
    ]
