# Generated by Django 4.2.4 on 2025-01-29 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0007_alter_sensorstatus_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='default_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='sensors.sensorstatus', verbose_name='Статус по умолчанию'),
        ),
    ]
