# Generated by Django 4.2.4 on 2025-02-06 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0008_sensor_default_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensorstatus',
            name='status_type',
            field=models.CharField(choices=[('WORK', 'Работа'), ('PAUSE', 'Тех. пауза'), ('STOP', 'Остановка'), ('OFFLINE', 'Отключен')], default='PAUSE', max_length=15, verbose_name='Тип статуса'),
            preserve_default=False,
        ),
    ]
